import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import type { Land, User } from "./api";
import { api, isOfflineDemo } from "./api";

const naira = (kobo: number) => `₦${(kobo / 100).toLocaleString("en-NG", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const shortDate = (iso: string) => new Intl.DateTimeFormat("en-NG", { dateStyle: "medium", timeStyle: "short" }).format(new Date(iso));

export function LevyManagementPage() {
  const client = useQueryClient(); const { data: lands = [], isLoading } = useQuery({ queryKey: ["levy-lands"], queryFn: () => api<Land[]>("/lands") });
  const [values, setValues] = useState<Record<string, string>>({}); const [message, setMessage] = useState("");
  const update = useMutation({ mutationFn: ({ propertyId, levyKobo }: { propertyId: string; levyKobo: number }) => api<Land>(`/lands/${propertyId}/levies`, { method: "POST", body: JSON.stringify({ levyKobo }) }), onSuccess: (land) => { setMessage(`${land.propertyId} levy updated to ${naira(land.outstandingLevyKobo)}.`); void client.invalidateQueries({ queryKey: ["levy-lands"] }); } });
  return <><div className="page-heading"><div><span className="eyebrow">Government stewardship</span><h1>Levy management</h1><p>Update outstanding land levies in simulated kobo values.</p></div></div>{message && <div className="success-box">{message}</div>}<section className="panel table-panel"><div className="table-head levy-head"><span>Parcel</span><span>Location</span><span>Current levy</span><span>Update</span></div>{isLoading ? <div className="empty">Loading levy records…</div> : lands.map((land) => <div className="table-row levy-row" key={land.propertyId}><strong><Link to={`/lands/${land.propertyId}`} className="text-link">{land.propertyId}</Link></strong><span>{land.state} · {land.lga}</span><span className={land.outstandingLevyKobo ? "danger-text" : ""}>{naira(land.outstandingLevyKobo)}</span><div className="levy-action"><input aria-label={`Levy for ${land.propertyId}`} type="number" min="0" step="0.01" placeholder="₦" value={values[land.propertyId] || ""} onChange={(event) => setValues({ ...values, [land.propertyId]: event.target.value })} /><button className="secondary" disabled={update.isPending || values[land.propertyId] === undefined || values[land.propertyId] === ""} onClick={() => void update.mutate({ propertyId: land.propertyId, levyKobo: Math.round(Number(values[land.propertyId]) * 100) })}>Save</button></div></div>)}</section></>;
}

type HealthResult = { label: string; status: string; detail: string; mode?: string };
export function SystemHealthPage() {
  const client = useQueryClient(); const { data, isLoading, refetch } = useQuery({ queryKey: ["system-health"], queryFn: async () => { const paths = [["Application API", "/health"], ["Synthetic identity", "/health/identity"], ["Document vault", "/health/ipfs"]] as const; const results: HealthResult[] = []; for (const [label, path] of paths) { try { const value = await api<{ status: string; detail?: string; mode?: string }>(path); results.push({ label, status: value.status, detail: value.detail || "Available", mode: value.mode }); } catch (error) { results.push({ label, status: "unavailable", detail: error instanceof Error ? error.message : "Unavailable" }); } } return results; } });
  const reset = useMutation({ mutationFn: () => api<{ reset: boolean }>("/demo/reset", { method: "POST" }), onSuccess: () => { window.location.assign("/login"); } });
  return <><div className="page-heading"><div><span className="eyebrow">Administrator workspace</span><h1>System health</h1><p>Service availability for the current local demonstration mode.</p></div><button className="secondary" onClick={() => void refetch()}>Refresh status</button></div><section className="service-grid">{isLoading ? <div className="empty">Checking local services…</div> : data?.map((service) => <div className="panel health-card" key={service.label}><div className="health-card-top"><span className="service-icon">⌘</span><span className={`status-pill ${service.status === "ok" ? "success" : "amber"}`}>{service.status}</span></div><h2>{service.label}</h2><p>{service.detail}</p>{service.mode && <small>Mode · {service.mode}</small>}</div>)}</section><section className="panel reset-panel"><div><span className="eyebrow">Development only</span><h2>Reset browser demo</h2><p>Clears local synthetic data and returns to the login screen. No production data is affected.</p></div><button className="secondary danger-button" disabled={!isOfflineDemo || reset.isPending} onClick={() => void reset.mutate()}>{isOfflineDemo ? "Reset local demo" : "Offline mode only"}</button></section></>;
}

export function ProfilePage() {
  const { data: user } = useQuery({ queryKey: ["profile"], queryFn: () => api<User>("/auth/me") });
  if (!user) return <div className="empty">Loading profile…</div>;
  return <><div className="page-heading"><div><span className="eyebrow">Signed-in identity</span><h1>Profile</h1><p>Your local application account and synthetic organisation identity.</p></div></div><section className="panel profile-panel"><div className="profile-hero"><div className="avatar large-avatar">{user.fullName.split(" ").map((part) => part[0]).join("").slice(0, 2)}</div><div><span className="eyebrow">{user.organisation}</span><h2>{user.fullName}</h2><p>{user.username} · {user.role.replaceAll("_", " ")}</p></div></div><div className="detail-grid profile-grid"><div><span>Synthetic NIN</span><strong>{user.nin.slice(0, 2)}••••{user.nin.slice(-2)}</strong></div><div><span>Fabric identity label</span><strong>{user.fabricIdentityLabel}</strong></div><div><span>Account status</span><strong className="success-text">Active</strong></div><div><span>Environment</span><strong>{isOfflineDemo ? "Browser-local demo" : "Local API demo"}</strong></div></div><div className="profile-note">This profile is synthetic academic data. It is not a live NIMC identity and does not grant access to a government land registry.</div></section></>;
}

export function DocumentVerificationPage() {
  const { data: lands = [], isLoading } = useQuery({ queryKey: ["document-lands"], queryFn: () => api<Land[]>("/lands") }); const [propertyId, setPropertyId] = useState(""); const [file, setFile] = useState<File | null>(null); const [result, setResult] = useState(""); const verify = useMutation({ mutationFn: async () => { if (!propertyId || !file) throw new Error("Choose a parcel and candidate document"); const form = new FormData(); form.append("document", file); return api<{ status: string; detail: string; candidateCid: string }>(`/lands/${propertyId}/verify-document`, { method: "POST", body: form }); }, onSuccess: (value) => setResult(`${value.status}: ${value.detail}`) });
  return <><div className="page-heading"><div><span className="eyebrow">Document vault</span><h1>Verify a land document</h1><p>Compare a candidate file against the CID recorded on a parcel.</p></div></div><section className="panel form-panel verification-panel"><label>Parcel record<select value={propertyId} onChange={(event) => setPropertyId(event.target.value)}><option value="">{isLoading ? "Loading parcels…" : "Choose a parcel"}</option>{lands.map((land) => <option value={land.propertyId} key={land.propertyId}>{land.propertyId} · {land.address}</option>)}</select></label>{propertyId && <div className="selected-record">{(() => { const land = lands.find((item) => item.propertyId === propertyId); return land ? <><strong>{land.propertyId}</strong><span>On-record document: {land.documentCid ? `${land.documentName} · ${land.documentCid}` : "No CID attached yet"}</span></> : null; })()}</div>}<label>Candidate document<input type="file" accept=".pdf,.png,.jpg,.jpeg,application/pdf,image/png,image/jpeg" onChange={(event) => setFile(event.target.files?.[0] || null)} /></label>{verify.error && <div className="error-box">{verify.error instanceof Error ? verify.error.message : "Verification failed"}</div>}{result && <div className={`success-box ${result.startsWith("MISMATCH") ? "mismatch-box" : ""}`}>{result}</div>}<button className="primary" disabled={verify.isPending || !propertyId || !file} onClick={() => void verify.mutate()}>{verify.isPending ? "Comparing CID…" : "Verify document"}</button></section></>;
}
