import type { Land, Transaction, User } from "./api";

type DemoAudit = { id: string; action: string; actor: string; organisation: User["organisation"]; propertyId?: string; status: "SUCCESS" | "FAILED"; timestamp: string; detail: string };
type StoredDocument = { base64: string; mimeType: string; filename: string };
type DemoState = { sessionUserId: string | null; lands: Land[]; transactions: Transaction[]; audit: DemoAudit[]; documents: Record<string, StoredDocument> };

// A versioned key deliberately starts the static deployment with a clean register.
// Existing development browser data remains untouched under the previous key.
const STORAGE_KEY = "blms-offline-demo-v2";
const now = () => new Date().toISOString();
const id = (prefix: string) => { const randomId = globalThis.crypto?.randomUUID?.(); return `${prefix}-${randomId?.slice(0, 8) || Math.random().toString(16).slice(2, 10)}`; };
const users: Array<User & { password: string }> = [
  { id: "USR-001", username: "citizen.seller", password: "Citizen123!", fullName: "Amina Yusuf", role: "CITIZEN", organisation: "CitizenOrg", nin: "10000000001", fabricIdentityLabel: "citizen.seller", active: true },
  { id: "USR-002", username: "citizen.buyer", password: "Citizen123!", fullName: "Chinedu Okafor", role: "CITIZEN", organisation: "CitizenOrg", nin: "10000000002", fabricIdentityLabel: "citizen.buyer", active: true },
  { id: "USR-003", username: "government.officer", password: "Government123!", fullName: "Bola Adeyemi", role: "GOVERNMENT_OFFICER", organisation: "GovernmentOrg", nin: "20000000001", fabricIdentityLabel: "government.officer", active: true },
  { id: "USR-004", username: "admin", password: "Admin123!", fullName: "Ifeoma Nwosu", role: "ADMIN", organisation: "GovernmentOrg", nin: "20000000002", fabricIdentityLabel: "admin", active: true }
];
const publicUser = (user: User & { password: string }): User => { const { password: _password, ...safe } = user; return safe; };
const initialState = (): DemoState => ({ sessionUserId: null, lands: [], transactions: [], audit: [], documents: {} });
const readState = (): DemoState => { try { const saved = localStorage.getItem(STORAGE_KEY); return saved ? JSON.parse(saved) as DemoState : initialState(); } catch { return initialState(); } };
const writeState = (state: DemoState) => localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
const currentUser = (state: DemoState) => { const user = users.find((item) => item.id === state.sessionUserId); return user ? publicUser(user) : null; };
const bodyOf = (init?: RequestInit) => typeof init?.body === "string" ? JSON.parse(init.body) as Record<string, unknown> : {};
const fail = (message: string): never => { throw new Error(message); };
const audit = (state: DemoState, user: User | null, action: string, detail: string, propertyId?: string) => { if (user) state.audit.unshift({ id: id("AUDIT"), action, actor: user.username, organisation: user.organisation, propertyId, status: "SUCCESS", timestamp: now(), detail }); };
const hashHex = async (bytes: BufferSource) => { const digest = await globalThis.crypto.subtle.digest("SHA-256", bytes); return Array.from(new Uint8Array(digest)).map((byte) => byte.toString(16).padStart(2, "0")).join(""); };
const validateFile = (file: File) => { if (file.size === 0 || file.size > 5 * 1024 * 1024) fail("Document must be between 1 byte and 5 MB"); const extension = file.name.toLowerCase().split(".").pop(); if (!extension || !["pdf", "png", "jpg", "jpeg"].includes(extension)) fail("Only PDF, PNG, and JPEG files are accepted"); return extension; };
const fileCid = async (file: File) => { const extension = validateFile(file); const bytes = new Uint8Array(await file.arrayBuffer()); const view = bytes; const signature = extension === "pdf" ? new TextDecoder().decode(view.slice(0, 5)) === "%PDF-" : extension === "png" ? Array.from(view.slice(0, 8)).join(",") === "137,80,78,71,13,10,26,10" : view[0] === 255 && view[1] === 216 && view[2] === 255; if (!signature) fail("The file extension does not match its content signature"); return { cid: `bafybeia${await hashHex(bytes)}`, bytes, mimeType: extension === "pdf" ? "application/pdf" : extension === "png" ? "image/png" : "image/jpeg" }; };
const fileFrom = (body: BodyInit | null | undefined, message: string): File => { const file = body instanceof FormData ? body.get("document") : null; if (!(file instanceof File)) return fail(message); return file; };
const base64From = (bytes: Uint8Array) => { let binary = ""; for (let index = 0; index < bytes.length; index += 0x8000) binary += String.fromCharCode(...bytes.slice(index, index + 0x8000)); return btoa(binary); };

export async function localDemoRequest<T>(path: string, init?: RequestInit): Promise<T> {
  const state = readState(); const user = currentUser(state); const [pathname, queryString] = path.split("?"); const query = new URLSearchParams(queryString || ""); const method = init?.method || "GET"; const segments = pathname.split("/").filter(Boolean); const json = bodyOf(init);
  if (pathname === "/auth/login" && method === "POST") { const found = users.find((item) => item.username === json.username && item.password === json.password); if (!found) return fail("Invalid username or password"); state.sessionUserId = found.id; audit(state, publicUser(found), "LOGIN", "Offline demo session created"); writeState(state); return publicUser(found) as T; }
  if (pathname === "/auth/logout" && method === "POST") { state.sessionUserId = null; writeState(state); return { loggedOut: true } as T; }
  if (pathname === "/auth/me") { if (!user) fail("Authentication required"); return user as T; }
  if (pathname === "/health") return { status: "ok", mode: "offline-browser", services: { api: "local", ledger: "localStorage", identity: "synthetic", ipfs: "content-addressed-local" } } as T;
  if (pathname === "/health/identity") return { status: "ok", mode: "in-browser-synthetic", records: 200, detail: "No live NIMC connection" } as T;
  if (pathname === "/health/ipfs") return { status: "ok", mode: "browser-content-addressed", detail: "No external IPFS service required in offline demo" } as T;
  const authedUser = user || fail("Authentication required");
  if (pathname === "/demo/reset" && method === "POST") { if (authedUser.role !== "ADMIN") return fail("Administrator permission required"); writeState(initialState()); return { reset: true } as T; }
  if (pathname === "/lands" && method === "GET") { const search = (query.get("search") || "").toLowerCase(); return state.lands.filter((land) => !search || [land.propertyId, land.parcelNumber, land.titleNumber, land.state, land.lga, land.ownerName, land.status].some((value) => value.toLowerCase().includes(search))) as T; }
  if (pathname === "/lands/mine") return state.lands.filter((land) => land.ownerNinRef === `nin-ref-${authedUser.nin}`) as T;
  if (pathname === "/transactions") return [...state.transactions].sort((a, b) => b.timestamp.localeCompare(a.timestamp)) as T;
  if (pathname === "/audit") return state.audit as T;
  if (pathname === "/revenue/summary") { if (authedUser.role === "CITIZEN") return fail("You do not have permission for this action"); const transfers = state.transactions.filter((transaction) => transaction.action === "LAND_TRANSFERRED"); return { totalRevenueKobo: transfers.reduce((sum, transaction) => sum + Math.floor((transaction.amountKobo || 0) * 5 / 100), 0), transferCount: transfers.length } as T; }
  if (pathname === "/lands" && method === "POST") { const land: Land = { propertyId: id("PROP"), parcelNumber: String(json.parcelNumber), titleNumber: String(json.titleNumber), ownerNinRef: `nin-ref-${authedUser.nin}`, ownerName: authedUser.fullName, state: String(json.state), lga: String(json.lga), address: String(json.address), latitude: Number(json.latitude), longitude: Number(json.longitude), sizeSqM: Number(json.sizeSqM), assessedValueKobo: Number(json.assessedValueKobo), askingPriceKobo: 0, outstandingLevyKobo: 0, documentCid: null, documentName: null, status: "REGISTERED", listedForSale: false, createdAt: now(), updatedAt: now(), version: 1 }; if (state.lands.some((item) => item.parcelNumber === land.parcelNumber || item.titleNumber === land.titleNumber)) return fail("A parcel or title number already exists"); state.lands.push(land); state.transactions.unshift({ id: id("TX"), propertyId: land.propertyId, action: "REGISTER_LAND", timestamp: now(), status: "SUCCESS", detail: "Land registered in offline browser ledger" }); audit(state, authedUser, "REGISTER_LAND", "Land registered", land.propertyId); writeState(state); return land as T; }
  const propertyId = segments[1]; const land = state.lands.find((item) => item.propertyId === propertyId) || fail("Property not found");
  if (segments[2] === "history") return state.transactions.filter((transaction) => transaction.propertyId === propertyId).sort((a, b) => b.timestamp.localeCompare(a.timestamp)) as T;
  if (segments[2] === "list" && method === "POST") { if (land.ownerNinRef !== `nin-ref-${authedUser.nin}`) return fail("Only the current owner can list this property"); const askingPriceKobo = Number(json.askingPriceKobo); if (!Number.isInteger(askingPriceKobo) || askingPriceKobo <= 0) return fail("Asking price must be a positive integer in kobo"); land.askingPriceKobo = askingPriceKobo; land.listedForSale = true; land.updatedAt = now(); land.version++; state.transactions.unshift({ id: id("TX"), propertyId, action: "LIST_PROPERTY", timestamp: now(), status: "SUCCESS", detail: "Property listed for sale" }); audit(state, authedUser, "LIST_PROPERTY", "Property listed", propertyId); writeState(state); return land as T; }
  if (segments[2] === "list" && method === "DELETE") { if (land.ownerNinRef !== `nin-ref-${authedUser.nin}`) return fail("Only the current owner can cancel this listing"); land.askingPriceKobo = 0; land.listedForSale = false; land.updatedAt = now(); land.version++; state.transactions.unshift({ id: id("TX"), propertyId, action: "CANCEL_LISTING", timestamp: now(), status: "SUCCESS", detail: "Property listing cancelled" }); audit(state, authedUser, "CANCEL_LISTING", "Listing cancelled", propertyId); writeState(state); return land as T; }
  if (segments[2] === "purchase" && method === "POST") { if (authedUser.role !== "CITIZEN") return fail("You do not have permission for this action"); if (!land.listedForSale) return fail("Property is not listed for sale"); if (land.ownerNinRef === `nin-ref-${authedUser.nin}`) return fail("The current owner cannot purchase the same property"); const seller = land.ownerName; const feeKobo = Math.floor(land.askingPriceKobo * 5 / 100); const sellerProceedsKobo = land.askingPriceKobo - feeKobo; land.ownerNinRef = `nin-ref-${authedUser.nin}`; land.ownerName = authedUser.fullName; land.listedForSale = false; land.askingPriceKobo = 0; land.status = "TRANSFERRED"; land.updatedAt = now(); land.version++; const transaction: Transaction = { id: id("TX"), propertyId, action: "LAND_TRANSFERRED", from: seller, to: authedUser.fullName, amountKobo: land.assessedValueKobo, timestamp: now(), status: "SUCCESS", detail: "SIMULATED — NO FUNDS MOVED" }; state.transactions.unshift(transaction); audit(state, authedUser, "PURCHASE", transaction.detail, propertyId); writeState(state); return { land, transaction, feeKobo, sellerProceedsKobo } as T; }
  if (segments[2] === "document" && method === "POST") { const file = fileFrom(init?.body, "Attach a PDF, PNG, or JPEG document"); if (land.ownerNinRef !== `nin-ref-${authedUser.nin}` && authedUser.role === "CITIZEN") return fail("Only the current owner can attach a land document"); const result = await fileCid(file); state.documents[result.cid] = { base64: base64From(result.bytes), mimeType: result.mimeType, filename: file.name.replace(/[^a-zA-Z0-9._-]/g, "_") }; land.documentCid = result.cid; land.documentName = file.name; land.updatedAt = now(); land.version++; audit(state, authedUser, "DOCUMENT_UPLOAD", `Document stored as ${result.cid}`, propertyId); writeState(state); return { land, cid: result.cid, filename: file.name, mimeType: result.mimeType } as T; }
  if (segments[2] === "verify-document" && method === "POST") { const file = fileFrom(init?.body, "Attach a candidate document"); const result = await fileCid(file); const status = land.documentCid && land.documentCid === result.cid ? "MATCH" : "MISMATCH"; audit(state, authedUser, "DOCUMENT_VERIFY", `${status} document verification`, propertyId); writeState(state); return { status, candidateCid: result.cid, expectedCid: land.documentCid, detail: status === "MATCH" ? "Candidate content matches the on-record CID" : "Candidate content does not match the on-record CID" } as T; }
  if (segments[2] === "levies" && method === "POST") { if (authedUser.role === "CITIZEN") return fail("Government authorisation required"); land.outstandingLevyKobo = Number(json.levyKobo); land.updatedAt = now(); land.version++; audit(state, authedUser, "UPDATE_LEVY", "Levy updated", propertyId); writeState(state); return land as T; }
  if (segments.length === 2 && method === "GET") return land as T;
  return fail("Route not found");
}

export const resetLocalDemo = () => localStorage.removeItem(STORAGE_KEY);
