import React, { createContext, useContext, useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { QueryClient, QueryClientProvider, useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BrowserRouter, Link, NavLink, Navigate, Route, Routes, useLocation, useNavigate, useParams } from "react-router-dom";
import { useForm } from "react-hook-form";
import type { Land, Transaction, User } from "./api";
import { api, isOfflineDemo } from "./api";
import { DocumentVerificationPage, LevyManagementPage, ProfilePage, SystemHealthPage } from "./featurePages";
import "@fontsource-variable/ibm-plex-sans/wght.css";
import "@fontsource/ibm-plex-mono/400.css";
import "@fontsource/ibm-plex-mono/500.css";
import "./styles.css";

const queryClient = new QueryClient();
const AuthContext = createContext<{ user: User | null; loading: boolean; login: (username: string, password: string) => Promise<void>; logout: () => Promise<void> }>({ user: null, loading: true, login: async () => {}, logout: async () => {} });
const useAuth = () => useContext(AuthContext);
const naira = (kobo: number) => `₦${(kobo / 100).toLocaleString("en-NG", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const shortDate = (iso: string) => new Intl.DateTimeFormat("en-NG", { dateStyle: "medium", timeStyle: "short" }).format(new Date(iso));
const roleLabel = (role: User["role"]) => role === "GOVERNMENT_OFFICER" ? "Government officer" : role === "ADMIN" ? "Administrator" : "Citizen";

function AuthProvider({ children }: { children: React.ReactNode }) {
  const [user, setUser] = useState<User | null>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { api<{ user: User | null }>("/auth/session").then((session) => setUser(session.user)).catch(() => setUser(null)).finally(() => setLoading(false)); }, []);
  const value = useMemo(() => ({
    user, loading,
    login: async (username: string, password: string) => setUser(await api<User>("/auth/login", { method: "POST", body: JSON.stringify({ username, password }) })),
    logout: async () => { await api("/auth/logout", { method: "POST" }); setUser(null); }
  }), [user, loading]);
  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>;
}

function AppShell() {
  const { user, loading, logout } = useAuth();
  const location = useLocation();
  const [menuOpen, setMenuOpen] = useState(false);
  useEffect(() => { setMenuOpen(false); }, [location.pathname]);
  useEffect(() => {
    if (!menuOpen) return;
    const closeOnEscape = (event: KeyboardEvent) => { if (event.key === "Escape") setMenuOpen(false); };
    document.addEventListener("keydown", closeOnEscape);
    return () => document.removeEventListener("keydown", closeOnEscape);
  }, [menuOpen]);
  if (loading) return <div className="loading-screen">Unlocking the registry…</div>;
  if (!user) return <Navigate to="/login" state={{ from: location.pathname }} replace />;
  const government = user.role !== "CITIZEN";
  const page = location.pathname === "/" ? "Registry overview" : location.pathname.slice(1).split("/").map((part) => part.replaceAll("-", " ")).join(" / ");
  return <div className="app-frame">
    <aside className={`sidebar${menuOpen ? " is-open" : ""}`} aria-label="Primary navigation">
      <Link to="/" className="brand"><span className="brand-mark">BL</span><span><strong>Blockland</strong><small>Land registry protocol</small></span></Link>
      <button className="menu-close" type="button" onClick={() => setMenuOpen(false)} aria-label="Close navigation">×</button>
      <div className="mode-badge"><span className="pulse" /> {isOfflineDemo ? "LOCAL LEDGER" : "PRIVATE API"}</div>
      <nav className="nav" onClick={() => setMenuOpen(false)}>
        <span className="nav-label">Registry</span>
        <NavLink to="/" end><span>◈</span>Overview</NavLink>
        <NavLink to="/lands"><span>▦</span>Parcel records</NavLink>
        <NavLink to="/marketplace"><span>◌</span>Marketplace</NavLink>
        <NavLink to="/register"><span>＋</span>Register parcel</NavLink>
        <span className="nav-label section-label">Proof desk</span>
        <NavLink to="/documents"><span>⌬</span>Document proof</NavLink>
        <NavLink to="/profile"><span>◉</span>Identity profile</NavLink>
        {government && <><span className="nav-label section-label">Stewardship</span><NavLink to="/levies"><span>₦</span>Levy management</NavLink><NavLink to="/revenue"><span>↗</span>Revenue summary</NavLink><NavLink to="/audit"><span>≡</span>Audit trail</NavLink></>}
        {user.role === "ADMIN" && <NavLink to="/system-health"><span>◍</span>System health</NavLink>}
      </nav>
      <div className="sidebar-foot"><div className="avatar">{user.fullName.split(" ").map((x) => x[0]).join("").slice(0, 2)}</div><div><strong>{user.fullName}</strong><small>{roleLabel(user.role)}</small></div><button className="icon-button" type="button" onClick={() => void logout()} aria-label="Log out">↗</button></div>
    </aside>
    <button className={`menu-overlay${menuOpen ? " is-visible" : ""}`} type="button" onClick={() => setMenuOpen(false)} aria-label="Close navigation" />
    <main className="main"><header className="topbar"><button className="menu-trigger" type="button" onClick={() => setMenuOpen(true)} aria-label="Open navigation"><span /><span /><span /></button><div><span className="eyebrow">{government ? "Authority node" : "Personal node"}</span><span className="crumb"> / {page}</span></div><div className="topbar-meta"><span className="health-dot" /> Browser-local · Africa/Lagos</div></header><div className="content"><Routes><Route path="/" element={<Dashboard />} /><Route path="/lands" element={<LandsPage />} /><Route path="/lands/:propertyId" element={<PropertyPage />} /><Route path="/marketplace" element={<Marketplace />} /><Route path="/register" element={<RegisterPage />} /><Route path="/documents" element={<DocumentVerificationPage />} /><Route path="/profile" element={<ProfilePage />} /><Route path="/levies" element={<LevyManagementPage />} /><Route path="/revenue" element={<RevenuePage />} /><Route path="/audit" element={<AuditPage />} /><Route path="/system-health" element={<SystemHealthPage />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></div></main>
  </div>;
}

// The login page is intentionally retained as-is; the new visual system begins after sign-in.
function Login() {
  const { user, login } = useAuth(); const navigate = useNavigate(); const [error, setError] = useState(""); const [showDemo, setShowDemo] = useState(false);
  const { register, handleSubmit, formState: { isSubmitting } } = useForm<{ username: string; password: string }>({ defaultValues: { username: "citizen.seller", password: "Citizen123!" } });
  if (user) return <Navigate to="/" replace />;
  return <main className="login-page"><div className="login-aside"><span className="brand-mark large">BL</span><p className="eyebrow light">Blockchain land registry</p><h1>Know the record.<br /><em>Trust the transfer.</em></h1><p className="login-copy">A research prototype for transparent land administration, built around shared records, clear ownership, and accountable public service.</p><div className="login-stamp">Synthetic academic data<br /><strong>No live government or payment systems</strong></div></div><section className="login-card"><div className="login-heading"><span className="eyebrow">Registry Desk</span><h2>Sign in to your workspace</h2><p>Use a seeded development account to explore the local demonstration.</p></div><form onSubmit={handleSubmit(async (values) => { try { await login(values.username, values.password); navigate("/"); } catch (e) { setError(e instanceof Error ? e.message : "Unable to sign in"); } })}><label>Username<input {...register("username", { required: true })} autoComplete="username" /></label><label>Password<input {...register("password", { required: true })} type="password" autoComplete="current-password" /></label>{error && <div className="error-box">{error}</div>}<button className="primary full" disabled={isSubmitting}>{isSubmitting ? "Opening…" : "Open registry desk"}</button></form><button className="demo-toggle" type="button" onClick={() => setShowDemo(!showDemo)}>{showDemo ? "Hide demo accounts" : "Show demo accounts"}</button>{showDemo && <div className="demo-accounts"><strong>Development accounts only</strong><span>citizen.seller / Citizen123!</span><span>citizen.buyer / Citizen123!</span><span>government.officer / Government123!</span><span>admin / Admin123!</span></div>}</section></main>;
}

function Dashboard() {
  const { user } = useAuth(); const { data: lands = [], isLoading } = useQuery({ queryKey: ["lands"], queryFn: () => api<Land[]>("/lands") }); const { data: transactions = [] } = useQuery({ queryKey: ["transactions"], queryFn: () => api<Transaction[]>("/transactions") });
  const mine = lands.filter((land) => land.ownerNinRef === `nin-ref-${user?.nin}`); const listed = lands.filter((land) => land.listedForSale); const government = user?.role !== "CITIZEN";
  const metrics = government ? [["Registered parcels", lands.length, "All records in this node"], ["Open listings", listed.length, "Available for transfer"], ["Levy flags", lands.filter((land) => land.outstandingLevyKobo > 0).length, "Require review"]] : [["My parcels", mine.length, "Current title records"], ["My listings", mine.filter((land) => land.listedForSale).length, "Visible in marketplace"], ["Actions pending", 0, "No approval required"]];
  const register = government ? lands : mine;
  return <>{isLoading ? <div className="empty">Synchronising the local register…</div> : <>
    <section className="command-hero"><div className="hero-copy"><span className="eyebrow">{shortDate(new Date().toISOString())} · encrypted workspace</span><h1>Land records,<br /><em>made legible.</em></h1><p>{government ? "Monitor the local land register from a single authority node." : "Own a clear, traceable view of every parcel connected to your identity."}</p><div className="hero-actions"><Link className="primary" to="/register">Register a parcel <span>→</span></Link><Link className="quiet-button" to="/lands">Explore register</Link></div></div><div className="cadastre-map" aria-hidden="true"><span className="map-chip">BLMS / LOCAL</span><span className="map-cross cross-one" /><span className="map-cross cross-two" /><span className="map-parcel parcel-a" /><span className="map-parcel parcel-b" /><span className="map-parcel parcel-c" /><div className="map-node"><i /> SECURE<br /><strong>REGISTRY NODE</strong></div></div></section>
    <section className="metric-grid">{metrics.map(([label, value, note]) => <div className="metric" key={String(label)}><span>{label}</span><strong>{value}</strong><small>{note}</small><i /></div>)}<div className="metric ledger-metric"><span>Ledger status</span><strong>LOCAL</strong><small>Private browser ledger active</small><i /></div></section>
    <section className="dashboard-grid"><section className="panel record-panel"><div className="panel-heading"><div><span className="eyebrow">Registry pulse</span><h2>{government ? "Latest parcel records" : "My parcel records"}</h2></div><Link to="/lands" className="text-link">Full register →</Link></div>{register.length ? register.slice(0, 4).map((land) => <LandRow key={land.propertyId} land={land} />) : <EmptyState title="Your register is clear" copy="Start with a parcel record. Its ownership, proof, and history will remain here." action="Register a parcel" to="/register" />}</section><section className="panel network-panel"><div className="panel-heading"><div><span className="eyebrow">Network posture</span><h2>Local verification</h2></div><span className="status-pill success">Private</span></div><NetworkRow glyph="◉" title="Registry interface" detail="Ready in this browser" status="Active" /><NetworkRow glyph="⌬" title="Proof vault" detail="Content-addressed locally" status="Ready" /><NetworkRow glyph="▦" title="Fabric connector" detail="Optional deployment layer" status="Standby" muted /></section></section>
    <section className="panel activity-panel"><div className="panel-heading"><div><span className="eyebrow">Append-only activity</span><h2>Registry log</h2></div><Link to="/audit" className="text-link">Open audit trail →</Link></div>{transactions.length ? transactions.slice(0, 5).map((transaction) => <div className="activity-row" key={transaction.id}><span className="activity-mark">{transaction.action === "LAND_TRANSFERRED" ? "↗" : "＋"}</span><div><strong>{transaction.action.replaceAll("_", " ")}</strong><small>{transaction.propertyId} · {transaction.detail}</small></div><time>{shortDate(transaction.timestamp)}</time></div>) : <EmptyState title="No registry activity" copy="The first action will appear here once a parcel is created or updated." />}</section>
  </>}</>;
}

function NetworkRow({ glyph, title, detail, status, muted = false }: { glyph: string; title: string; detail: string; status: string; muted?: boolean }) { return <div className="service-row"><span className="service-icon">{glyph}</span><div><strong>{title}</strong><small>{detail}</small></div><span className={`status-pill ${muted ? "muted" : "success"}`}>{status}</span></div>; }
function EmptyState({ title, copy, action, to }: { title: string; copy: string; action?: string; to?: string }) { return <div className="empty-state"><span>◇</span><div><strong>{title}</strong><p>{copy}</p>{action && to && <Link className="text-link" to={to}>{action} →</Link>}</div></div>; }
function LandRow({ land }: { land: Land }) { return <Link className="land-row" to={`/lands/${land.propertyId}`}><div className="parcel-icon"><i /></div><div><strong>{land.propertyId}</strong><span>{land.address}</span></div><div className="land-row-meta"><span>{land.state} · {land.lga}</span><span className={`status-pill ${land.listedForSale ? "amber" : "muted"}`}>{land.listedForSale ? "Listed" : "Held"}</span></div><span className="row-arrow">→</span></Link>; }

function LandsPage() { const [search, setSearch] = useState(""); const { data = [], isLoading } = useQuery({ queryKey: ["lands", search], queryFn: () => api<Land[]>(`/lands?search=${encodeURIComponent(search)}`) }); return <><PageHeading eyebrow="Land register" title="Parcel records" copy="Search every locally recorded title, location, and ownership reference." action="Register a parcel" to="/register" /><div className="toolbar"><div className="search-field">⌕<input placeholder="Search property, title, state, or owner…" value={search} onChange={(event) => setSearch(event.target.value)} /></div><span className="result-count">{data.length} record{data.length === 1 ? "" : "s"}</span></div><section className="panel record-panel">{isLoading ? <div className="empty">Searching the register…</div> : data.length ? data.map((land) => <LandRow key={land.propertyId} land={land} />) : <EmptyState title={search ? "No matching parcels" : "The register is clear"} copy={search ? "Try another parcel, title, location, or owner reference." : "No parcel data is preloaded. Create the first record when you are ready."} action={!search ? "Register the first parcel" : undefined} to={!search ? "/register" : undefined} />}</section></>; }
function Marketplace() { const { data = [], isLoading } = useQuery({ queryKey: ["lands", "marketplace"], queryFn: () => api<Land[]>("/lands") }); const listed = data.filter((land) => land.listedForSale); return <><PageHeading eyebrow="Transfer desk" title="Marketplace" copy="Review title records offered for transfer with a transparent local fee simulation." /><section className="market-grid">{isLoading ? <div className="empty">Loading transfer records…</div> : listed.length ? listed.map((land) => <Link to={`/lands/${land.propertyId}`} className="market-card" key={land.propertyId}><div className="market-top"><span className="status-pill amber">For sale</span><span>{land.state}</span></div><div className="market-grid-mark">{land.parcelNumber.slice(-2)}</div><h2>{land.propertyId}</h2><p>{land.address}</p><div className="market-detail"><span>Parcel number<strong>{land.parcelNumber}</strong></span><span>Asking price<strong>{naira(land.askingPriceKobo)}</strong></span></div><div className="market-footer">Open record <span>→</span></div></Link>) : <div className="panel market-empty"><EmptyState title="No open transfer records" copy="New listings will appear here once an owner makes a parcel available." to="/lands" action="Browse parcel records" /></div>}</section></>; }

function PropertyPage() {
  const { propertyId = "" } = useParams(); const { user } = useAuth(); const client = useQueryClient(); const { data: land, isLoading } = useQuery({ queryKey: ["land", propertyId], queryFn: () => api<Land>(`/lands/${propertyId}`) }); const { data: history = [] } = useQuery({ queryKey: ["history", propertyId], queryFn: () => api<Transaction[]>(`/lands/${propertyId}/history`), enabled: Boolean(land) }); const [message, setMessage] = useState("");
  const purchase = useMutation({ mutationFn: () => api<{ land: Land }>(`/lands/${propertyId}/purchase`, { method: "POST" }), onSuccess: () => { setMessage("Transfer recorded locally. No funds moved."); void client.invalidateQueries(); } });
  const listing = useMutation({ mutationFn: (askingPriceKobo: number) => api<Land>(`/lands/${propertyId}/list`, { method: "POST", body: JSON.stringify({ askingPriceKobo }) }), onSuccess: () => void client.invalidateQueries() });
  if (isLoading || !land) return <div className="empty">Opening parcel record…</div>;
  const isOwner = land.ownerNinRef === `nin-ref-${user?.nin}`;
  return <><Link to="/lands" className="back-link">← Back to parcel records</Link><div className="record-banner"><div><span className="eyebrow">Parcel record · {land.status}</span><h1>{land.propertyId}</h1><p>{land.address}</p></div><div className="record-banner-meta"><span className="status-pill success">Verified locally</span><code>v{land.version.toString().padStart(2, "0")}</code></div>{land.listedForSale && !isOwner && <button className="primary" type="button" onClick={() => void purchase.mutate()} disabled={purchase.isPending}>{purchase.isPending ? "Recording transfer…" : `Purchase · ${naira(land.askingPriceKobo)}`}</button>}</div>{message && <div className="success-box">{message}</div>}<div className="record-layout"><section className="panel record-card"><div className="record-card-top"><span className="eyebrow">Title holder</span><div className="seal">BL<br /><strong>LOCAL</strong></div></div><h2>{land.ownerName}</h2><p className="masked">Identity reference · {land.ownerNinRef.replace(/(nin-ref-\d{2})\d+/, "$1••••")}</p><div className="detail-grid"><Detail label="Parcel number" value={land.parcelNumber} /><Detail label="Title number" value={land.titleNumber} /><Detail label="State / LGA" value={`${land.state} · ${land.lga}`} /><Detail label="Surveyed size" value={`${land.sizeSqM.toLocaleString()} m²`} /><Detail label="Assessed value" value={naira(land.assessedValueKobo)} /><Detail label="Outstanding levy" value={naira(land.outstandingLevyKobo)} danger={Boolean(land.outstandingLevyKobo)} /></div>{isOwner && !land.listedForSale && <ListForm onSubmit={(value) => listing.mutate(value)} />}<DocumentControls propertyId={propertyId} land={land} onComplete={() => { void client.invalidateQueries(); }} /><div className="record-foot"><span>Updated {shortDate(land.updatedAt)}</span><span className="status-pill success">Record sealed</span></div></section><section className="panel history-card"><div className="panel-heading"><div><span className="eyebrow">Chain of custody</span><h2>Record history</h2></div></div>{history.length ? history.map((transaction) => <div className="history-row" key={transaction.id}><span className="history-dot" /><div><strong>{transaction.action.replaceAll("_", " ")}</strong><small>{transaction.detail}</small><time>{shortDate(transaction.timestamp)}</time></div></div>) : <EmptyState title="No recorded events" copy="This parcel is awaiting its first registry action." />}</section></div></>;
}

function Detail({ label, value, danger = false }: { label: string; value: string; danger?: boolean }) { return <div><span>{label}</span><strong className={danger ? "danger-text" : ""}>{value}</strong></div>; }
function DocumentControls({ propertyId, land, onComplete }: { propertyId: string; land: Land; onComplete: () => void }) { const [file, setFile] = useState<File | null>(null); const [result, setResult] = useState(""); const upload = useMutation({ mutationFn: async () => { if (!file) throw new Error("Choose a PDF, PNG, or JPEG first"); const form = new FormData(); form.append("document", file); return api<{ cid: string }>(`/lands/${propertyId}/document`, { method: "POST", body: form }); }, onSuccess: (data) => { setResult(`Proof stored as ${data.cid}`); onComplete(); } }); const verify = useMutation({ mutationFn: async () => { if (!file) throw new Error("Choose a candidate document first"); const form = new FormData(); form.append("document", file); return api<{ status: string; detail: string }>(`/lands/${propertyId}/verify-document`, { method: "POST", body: form }); }, onSuccess: (data) => setResult(`${data.status}: ${data.detail}`) }); return <div className="document-controls"><div><span className="eyebrow">Proof vault</span><h3>{land.documentCid ? "Content proof attached" : "No content proof yet"}</h3><small>{land.documentCid ? `${land.documentName} · ${land.documentCid}` : "PDF, PNG, or JPEG · maximum 5 MB"}</small></div><label className="file-picker">Choose file<input type="file" accept=".pdf,.png,.jpg,.jpeg,application/pdf,image/png,image/jpeg" onChange={(event) => setFile(event.target.files?.[0] || null)} /></label><div className="document-actions"><button className="secondary" type="button" onClick={() => void upload.mutate()} disabled={upload.isPending}>{upload.isPending ? "Sealing…" : "Seal document"}</button><button className="secondary" type="button" onClick={() => void verify.mutate()} disabled={verify.isPending}>{verify.isPending ? "Checking…" : "Verify proof"}</button></div>{(upload.error || verify.error) && <div className="error-box">{(upload.error || verify.error) instanceof Error ? (upload.error || verify.error)?.message : "Document action failed"}</div>}{result && <div className="document-result">{result}</div>}</div>; }
function ListForm({ onSubmit }: { onSubmit: (value: number) => void }) { const { register, handleSubmit } = useForm<{ askingPrice: number }>(); return <form className="inline-form" onSubmit={handleSubmit((value) => onSubmit(Math.round(Number(value.askingPrice) * 100)))}><label>List for sale (₦)<input type="number" step="0.01" {...register("askingPrice", { required: true, min: 1 })} /></label><button className="secondary">Open listing</button></form>; }
function RegisterPage() { const navigate = useNavigate(); const client = useQueryClient(); const [error, setError] = useState(""); const { register, handleSubmit, formState: { isSubmitting } } = useForm<{ parcelNumber: string; titleNumber: string; state: string; lga: string; address: string; latitude: number; longitude: number; sizeSqM: number; assessedValue: number }>(); return <><PageHeading eyebrow="New registry entry" title="Register a parcel" copy="Create a new local title record. Ownership is tied to your signed-in identity." /><section className="panel form-panel"><form onSubmit={handleSubmit(async (value) => { try { const land = await api<Land>("/lands", { method: "POST", body: JSON.stringify({ ...value, assessedValueKobo: Math.round(Number(value.assessedValue) * 100), latitude: Number(value.latitude), longitude: Number(value.longitude), sizeSqM: Number(value.sizeSqM) }) }); await client.invalidateQueries(); navigate(`/lands/${land.propertyId}`); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to register parcel"); } })}><div className="form-section"><span className="eyebrow">Title identifiers</span><div className="form-grid"><label>Parcel number<input {...register("parcelNumber", { required: true })} placeholder="LAG-IKE-0010" /></label><label>Title number<input {...register("titleNumber", { required: true })} placeholder="LND-2026-010" /></label></div></div><div className="form-section"><span className="eyebrow">Location</span><div className="form-grid"><label>State<input {...register("state", { required: true })} placeholder="Lagos" /></label><label>LGA<input {...register("lga", { required: true })} placeholder="Ikeja" /></label><label className="wide">Address<input {...register("address", { required: true })} placeholder="Street, district, city" /></label></div></div><div className="form-section"><span className="eyebrow">Survey and assessment</span><div className="form-grid"><label>Latitude<input type="number" step="any" {...register("latitude", { required: true })} placeholder="6.6018" /></label><label>Longitude<input type="number" step="any" {...register("longitude", { required: true })} placeholder="3.3515" /></label><label>Size (m²)<input type="number" step="any" {...register("sizeSqM", { required: true })} placeholder="620" /></label><label>Assessed value (₦)<input type="number" step="0.01" {...register("assessedValue", { required: true })} placeholder="185000000" /></label></div></div>{error && <div className="error-box">{error}</div>}<div className="form-actions"><span className="muted-copy">You can attach a content proof after creating the record.</span><button className="primary" disabled={isSubmitting}>{isSubmitting ? "Creating record…" : "Create registry entry"}</button></div></form></section></>; }
function PageHeading({ eyebrow, title, copy, action, to }: { eyebrow: string; title: string; copy: string; action?: string; to?: string }) { return <div className="page-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div>{action && to && <Link className="primary" to={to}>{action} <span>→</span></Link>}</div>; }
function AuditPage() { const { data = [] } = useQuery({ queryKey: ["audit"], queryFn: () => api<Array<{ id: string; action: string; actor: string; detail: string; timestamp: string }>>("/audit") }); return <><PageHeading eyebrow="Accountability" title="Audit trail" copy="Every local action is written to this browser-based audit log." /><section className="panel table-panel"><div className="table-head"><span>Action</span><span>Actor</span><span>Detail</span><span>Time</span></div>{data.length ? data.map((event) => <div className="table-row" key={event.id}><strong>{event.action.replaceAll("_", " ")}</strong><span>{event.actor}</span><span>{event.detail}</span><time>{shortDate(event.timestamp)}</time></div>) : <EmptyState title="No audit entries" copy="A signed-in action such as registering a parcel will create the first record." />}</section></>; }
function RevenuePage() { const { data } = useQuery({ queryKey: ["revenue"], queryFn: () => api<{ totalRevenueKobo: number; transferCount: number }>("/revenue/summary") }); return <><PageHeading eyebrow="Government stewardship" title="Revenue summary" copy="Transfer allocations are simulated locally; no funds are processed by this prototype." /><section className="revenue-callout"><span className="eyebrow">Settlement allocation</span><strong>{naira(data?.totalRevenueKobo || 0)}</strong><p>{data?.transferCount || 0} recorded transfer{data?.transferCount === 1 ? "" : "s"} · local simulation only</p></section></>; }
function Root() { return <AuthProvider><Routes><Route path="/login" element={<Login />} /><Route path="*" element={<AppShell />} /></Routes></AuthProvider>; }
createRoot(document.getElementById("root")!).render(<React.StrictMode><QueryClientProvider client={queryClient}><BrowserRouter><Root /></BrowserRouter></QueryClientProvider></React.StrictMode>);
