import test from "node:test";
import assert from "node:assert/strict";
import request from "supertest";
import { app } from "../src/app.js";

test("health identifies the explicit mock mode", async () => { const response = await request(app).get("/api/v1/health"); assert.equal(response.status, 200); assert.equal(response.body.data.mode, "mock"); });
test("seeded citizen can authenticate and query lands", async () => { const agent = request.agent(app); const login = await agent.post("/api/v1/auth/login").send({ username: "citizen.seller", password: "Citizen123!" }); assert.equal(login.status, 200); assert.equal(login.body.data.role, "CITIZEN"); const lands = await agent.get("/api/v1/lands"); assert.equal(lands.status, 200); assert.ok(lands.body.data.length >= 5); });
test("buyer can purchase a listed property and receive a simulated allocation", async () => { const agent = request.agent(app); await agent.post("/api/v1/auth/login").send({ username: "citizen.buyer", password: "Citizen123!" }); const purchase = await agent.post("/api/v1/lands/PROP-001/purchase"); assert.equal(purchase.status, 200); assert.match(purchase.body.data.transaction.detail, /SIMULATED/); assert.equal(purchase.body.data.land.listedForSale, false); });
test("authenticated user can inspect deterministic simulated ledger proof", async () => { const agent = request.agent(app); await agent.post("/api/v1/auth/login").send({ username: "citizen.seller", password: "Citizen123!" }); const proof = await agent.get("/api/v1/lands/PROP-001/proof"); assert.equal(proof.status, 200); assert.equal(proof.body.data.networkMode, "simulated-fabric"); assert.match(proof.body.data.blockHash, /^[a-f0-9]{64}$/); assert.ok(proof.body.data.endorsements.includes("GovernmentOrg.peer0.demo")); });
test("government role is required for revenue summary", async () => { const agent = request.agent(app); await agent.post("/api/v1/auth/login").send({ username: "citizen.seller", password: "Citizen123!" }); const response = await agent.get("/api/v1/revenue/summary"); assert.equal(response.status, 403); });
test("owner can attach a document and verify matching or altered content", async () => { const agent = request.agent(app); await agent.post("/api/v1/auth/login").send({ username: "citizen.seller", password: "Citizen123!" }); const original = Buffer.from("%PDF-1.4\nBLMS synthetic title document"); const upload = await agent.post("/api/v1/lands/PROP-002/document").attach("document", original, { filename: "title.pdf", contentType: "application/pdf" }); assert.equal(upload.status, 201); assert.match(upload.body.data.cid, /^bafybeia/); const match = await agent.post("/api/v1/lands/PROP-002/verify-document").attach("document", original, { filename: "title.pdf", contentType: "application/pdf" }); assert.equal(match.body.data.status, "MATCH"); const mismatch = await agent.post("/api/v1/lands/PROP-002/verify-document").attach("document", Buffer.from("%PDF-1.4\nchanged"), { filename: "altered.pdf", contentType: "application/pdf" }); assert.equal(mismatch.body.data.status, "MISMATCH"); });
